In [1]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)
print(array_list)

['1' '2' '3' '4' '5']


#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Ans.

In [2]:
print("Datatype of list_ => ",type(list_))
print("Datatype of array_list => ",type(array_list))

Datatype of list_ =>  <class 'list'>
Datatype of array_list =>  <class 'numpy.ndarray'>


---

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

Ans.

In [3]:
for i in range(len(list_)):
    print(type(list_[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [4]:
for i in range(len(array_list)):
    print(type(array_list[i]))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


---

#### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)  
Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Ans.

In [5]:
array_list = np.array(object = list_, dtype= int)
print(array_list)
type(array_list)

[1 2 3 4 5]


numpy.ndarray

The difference will be seen only in the elements of **array_list**, as they will convert form "str" into "int" datatype.

In [6]:
for i in range(len(array_list)):
    print(type(array_list[i]))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [7]:
for i in range(len(list_)):
    print(type(list_[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


---

Consider the below code to answer further questions:

In [8]:
import numpy as np
num_list = [[1, 2, 3] ,[4, 5, 6]]
num_array = np.array(object = num_list)

In [9]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

#### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape (ii) size

Ans.

In [10]:
print(f"shape of an array => {num_array.shape}")

shape of an array => (2, 3)


In [11]:
print(f"Size of an array => {num_array.size}")

Size of an array => 6


---

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

Ans.

In [12]:
num_arr = np.zeros((3,3))
num_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Ans.

In [13]:
num_arr = np.identity(5)
num_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])